# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
name: ant design

trigger:
  - master

resources:
  repositories:
  - repository: self
    fetchDepth: 1

jobs:
  - job: test
    pool:
      vmImage: 'Ubuntu-16.04'
    strategy:
      matrix:
        TEST_TYPE:
          env: TEST_TYPE=lint
        REACT=16-TEST_TYPE=test:dist:
          env: REACT=16 TEST_TYPE=test:dist
        REACT=16-TEST_TYPE=test:lib:
          env: REACT=16 TEST_TYPE=test:lib
        REACT=16-TEST_TYPE=test:es:
          env: REACT=16 TEST_TYPE=test:es
        REACT=16-TEST_TYPE=test:dom:
          env: REACT=16 TEST_TYPE=test:dom
        REACT=16-TEST_TYPE=test:node:
          env: REACT=16 TEST_TYPE=test:node
        REACT=15-TEST_TYPE=test:dist:
          env: REACT=15 TEST_TYPE=test:dist
        REACT=15-TEST_TYPE=test:lib: 
          env: REACT=15 TEST_TYPE=test:lib
        REACT=15-TEST_TYPE=test:es:
          env: REACT=15 TEST_TYPE=test:es
        REACT=15-TEST_TYPE=test:dom:
          env: REACT=15 TEST_TYPE=test:dom
        REACT=15-TEST_TYPE=test:node:
          env: REACT=15 TEST_TYPE=test:node
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '11.x'
      - script: npm install
      - script: scripts/install-react.sh
      - script: scripts/travis-script.sh
